### PR TITLE
V4l2 devices might not be named video

### LINKED ISSUE #312: Startup fails if camera is not named /dev/videox
I thought an additional issue might make sense as it differs from #310. As already stated in PR #311 

With udev and/or in containers it is possible to have the camera mounted where ever you want in the file system instead of just `/dev/videox`. I suggest the code should not make any assumptions about the possible paths

I didnt perform any tests yet but I think `v4l2-ctl --list-devices` will actually correctly list all devices even if they are not at `/dev/videox`

Example output for my system is:

```
Logitech Webcam C925e (usb-0000:12:00.0-1.3):
	/dev/video0
	/dev/video1
	/dev/media0
```

So apparently it finds the /dev/media0

### PR DESCRIPTION
**Pull request by flynneva**
Closes #312

### CODE REVIEW

**Comment by flynneva** [comment]
fyi @firesurfer this should resolve #312

File: include/usb_cam/utils.hpp [hunk 1]
```diff
@@ -146,31 +151,41 @@ inline std::map<std::string, v4l2_capability> available_devices()
   // Initialize vector of device strings to fill in
   std::map<std::string, v4l2_capability> v4l2_devices;
 
-  // V4L2 spec says there can only be a maximum of 64 devices
-  const uint8_t MAX_DEVICES = 64;
+  // Get a list of all v4l2 devices from /sys/class/video4linux
```
Comment (flynneva) [inline include/usb_cam/utils.hpp:154]: @firesurfer the list in `/sys/class/video4linux` should include all valid v4l2 devices I think...even if they are `/dev/media` devices

**Comment by firesurfer** [comment]
Hi @flynneva sorry I didn't get to test this PR yet. We are currently migrating to a new hardware setup and it will take sometime until I have the cameras ready again
